apache/flink-agents

tools/ut.sh

[hotfix] Fix the ut.sh for java tests

---

pom.xml
runtime/pom.xml
runtime/src/main/java/org/apache/flink/agents/runtime/env/EmbeddedPythonEnvironment.java
runtime/src/main/java/org/apache/flink/agents/runtime/env/PythonEnvironmentManager.java
runtime/src/test/java/org/apache/flink/agents/runtime/env/PythonEnvironmentManagerTest.java

Linked issue: #33
Adds support of python dependency management.
`PythonEnvironmentManagerTest`

[Feature][runtime] Adds support of Python Environment Manager

---

.asf.yaml

[infra] Add Hao Li as collaborator on github

---

.asf.yaml

[infra] Add Wenjin Xie, Xu Huang and Eugene as collaborators on github

---

.gitignore
api/src/main/java/org/apache/flink/agents/api/Action.java
api/src/main/java/org/apache/flink/agents/api/Agent.java
plan/pom.xml
plan/src/main/java/org/apache/flink/agents/plan/AgentPlan.java
plan/src/test/java/org/apache/flink/agents/plan/AgentPlanTest.java
plan/src/test/java/org/apache/flink/agents/plan/serializer/AgentPlanJsonSerializerTest.java
pom.xml
runtime/pom.xml

Linked issue: https://github.com/apache/flink-agents/issues/16
Add Java API for agent.
Unit test
Yes. Added agent and action api
Javadoc

[API][Java] agent java api

---

.asf.yaml

[infra] add Min Zhou, Weiqing Yang and Alan Zhang as collaborators on Github

---

plan/src/main/java/org/apache/flink/agents/plan/JavaFunction.java
python/flink_agents/api/runner_context.py
python/flink_agents/examples/my_agent.py
python/flink_agents/plan/function.py
python/flink_agents/plan/tests/compatibility/create_python_agent_plan_from_json.py
python/flink_agents/plan/tests/test_function.py
python/flink_agents/runtime/flink_runner_context.py
python/flink_agents/runtime/local_runner.py
python/flink_agents/runtime/tests/test_local_execution_environment.py
runtime/pom.xml
runtime/src/main/java/org/apache/flink/agents/runtime/context/RunnerContextImpl.java
runtime/src/main/java/org/apache/flink/agents/runtime/memory/MemoryObjectImpl.java
runtime/src/main/java/org/apache/flink/agents/runtime/operator/ActionExecutionOperator.java
runtime/src/main/java/org/apache/flink/agents/runtime/operator/ActionExecutionOperatorFactory.java
runtime/src/main/java/org/apache/flink/agents/runtime/operator/ActionTask.java
runtime/src/main/java/org/apache/flink/agents/runtime/operator/JavaActionTask.java
runtime/src/main/java/org/apache/flink/agents/runtime/python/context/PythonRunnerContextImpl.java
runtime/src/main/java/org/apache/flink/agents/runtime/python/operator/PythonActionTask.java
runtime/src/main/java/org/apache/flink/agents/runtime/python/operator/PythonGeneratorActionTask.java
runtime/src/main/java/org/apache/flink/agents/runtime/python/utils/PythonActionExecutor.java
runtime/src/main/java/org/apache/flink/agents/runtime/utils/StateUtil.java
runtime/src/test/java/org/apache/flink/agents/runtime/CompileUtilsTest.java
runtime/src/test/java/org/apache/flink/agents/runtime/RescalingITCase.java
runtime/src/test/java/org/apache/flink/agents/runtime/operator/ActionExecutionOperatorTest.java

Linked issue: #78 
Enable the agent and action to support asynchronous and parallel processing for improved performance. Details can be found in the #78 .
Added corresponding unit tests and e2e tests.
Yes, introduce runner_context#execute_async API
No, I'll add the relevant documentation in the future.

[API][Runtime] Support agent and action asynchronous execution

---

python/flink_agents/api/chat_models/chat_model.py
python/flink_agents/api/tools/tool.py
python/flink_agents/examples/chat_ollama_exmaple.py
python/flink_agents/integrations/chat_models/__init__.py
python/flink_agents/integrations/chat_models/ollama_chat_model.py
python/flink_agents/integrations/chat_models/tests/__init__.py
python/flink_agents/integrations/chat_models/tests/start_ollama_server.sh
python/flink_agents/integrations/chat_models/tests/test_ollama_chat_model.py
python/flink_agents/plan/tests/test_agent_plan.py
python/flink_agents/runtime/tests/test_built_in_actions.py
python/flink_agents/runtime/tests/test_get_resource_in_action.py
python/pyproject.toml

Linked issue: #89 
Add built-in ollama chat model in python.
unit test and integrate test
No
No

[Integration][ChatModel] Add built-in ollama chat model in python

---

api/pom.xml
api/src/main/java/org/apache/flink/agents/api/annotation/Action.java
api/src/main/java/org/apache/flink/agents/api/annotation/ChatModel.java
api/src/main/java/org/apache/flink/agents/api/annotation/Tool.java
api/src/main/java/org/apache/flink/agents/api/context/RunnerContext.java
api/src/main/java/org/apache/flink/agents/api/resource/Resource.java
api/src/main/java/org/apache/flink/agents/api/resource/ResourceType.java
api/src/main/java/org/apache/flink/agents/api/resource/SerializableResource.java
examples/src/main/java/org/apache/flink/agents/examples/SimpleAgent.java
plan/src/main/java/org/apache/flink/agents/plan/Action.java
plan/src/main/java/org/apache/flink/agents/plan/AgentPlan.java
plan/src/main/java/org/apache/flink/agents/plan/resourceprovider/JavaResourceProvider.java
plan/src/main/java/org/apache/flink/agents/plan/resourceprovider/JavaSerializableResourceProvider.java
plan/src/main/java/org/apache/flink/agents/plan/resourceprovider/PythonResourceProvider.java
plan/src/main/java/org/apache/flink/agents/plan/resourceprovider/PythonSerializableResourceProvider.java
plan/src/main/java/org/apache/flink/agents/plan/resourceprovider/ResourceProvider.java
plan/src/main/java/org/apache/flink/agents/plan/resourceprovider/SerializableResourceProvider.java
plan/src/test/java/org/apache/flink/agents/plan/AgentPlanTest.java
plan/src/test/java/org/apache/flink/agents/plan/compatibility/GenerateAgentPlanJson.java
plan/src/test/java/org/apache/flink/agents/plan/serializer/AgentPlanJsonSerializerTest.java
runtime/src/main/java/org/apache/flink/agents/runtime/context/RunnerContextImpl.java
runtime/src/main/java/org/apache/flink/agents/runtime/operator/ActionExecutionOperator.java
runtime/src/main/java/org/apache/flink/agents/runtime/python/context/PythonRunnerContextImpl.java
runtime/src/test/java/org/apache/flink/agents/runtime/RescalingITCase.java

Linked issue: #69 
Introduce resource and resource provider concept in java to mimic the same behavior in python. This is the first step to introduce Tool, chat_model and prompt.
Unit test added, however some of the code are not covered as we only have base class that is abstract which can't be instantiate for use.
Added resource and resource provider in java

[plan][runtime][java] Introduce Resource and Resource Provider in java

---

examples/pom.xml
examples/src/main/java/org/apache/flink/agents/examples/SimpleAgent.java
examples/src/main/java/org/apache/flink/agents/examples/TableIntegrationExample.java

Fix examples so they can run normally

[hotfix] fix examples can't execute

---

examples/src/main/java/org/apache/flink/agents/examples/DataStreamAgent.java
examples/src/main/java/org/apache/flink/agents/examples/DataStreamIntegrationExample.java
examples/src/main/java/org/apache/flink/agents/examples/MemoryObjectAgent.java
examples/src/main/java/org/apache/flink/agents/examples/MemoryObjectExample.java
examples/src/main/java/org/apache/flink/agents/examples/TableAgent.java
examples/src/main/java/org/apache/flink/agents/examples/TableIntegrationExample.java

Linked issue: #123 
Add test cases of Short-Term Memory in java.

[hotfix]Enrich test cases of Short-Term Memory in java

---

examples/src/main/java/org/apache/flink/agents/examples/AgentWithOllama.java
integrations/chat-models/ollama/src/main/java/org/apache/flink/agents/integrations/chatmodels/ollama/OllamaChatModelConnection.java
integrations/chat-models/ollama/src/main/java/org/apache/flink/agents/integrations/chatmodels/ollama/OllamaChatModelSetup.java

Fix ollama chat model compile error after refactor chat model api in java.

[hotfix] Adapt ollama integration after refactor chat model api.

---

docs/content/docs/try-flink-agents/installation.md
python/pyproject.toml

Linked issue: #xxx
Update installation instructions for Flink Agents with PyPI and source build details.

[docs] Update installation instructions for Flink Agents with PyPI and source build details

---

python/flink_agents/integrations/vector_stores/chroma/chroma_vector_store.py
python/flink_agents/integrations/vector_stores/chroma/tests/test_chroma_vector_store.py

Linked issue: #187
Support Chroma Cloud
unit test
- Add new config `api_key` to support Chroma cloud
n/a

[Feature] Support Chroma Cloud

---

python/flink_agents/integrations/chat_models/tests/test_tongyi_chat_model.py
python/flink_agents/integrations/chat_models/tongyi_chat_model.py

Updated the method to correctly extract reasoning content from the model output. Reference: https://help.aliyun.com/zh/model-studio/deep-thinking

[hotfix] fix reasoning extraction from Tongyi model

---

plan/src/test/java/org/apache/flink/agents/plan/compatibility/CreateJavaAgentPlanFromJson.java
python/flink_agents/api/agents/react_agent.py
python/flink_agents/api/prompts/prompt.py
python/flink_agents/api/resource.py
python/flink_agents/api/tests/mcp/test_mcp.py
python/flink_agents/api/tests/test_prompt.py
python/flink_agents/api/tests/test_tool.py
python/flink_agents/api/tools/mcp.py
python/flink_agents/api/tools/tool.py
python/flink_agents/examples/chat_model_example.py
python/flink_agents/examples/integrate_table_with_react_agent_example.py
python/flink_agents/examples/quickstart/agents/product_suggestion_agent.py
python/flink_agents/examples/quickstart/agents/review_analysis_agent.py
python/flink_agents/examples/react_agent_example.py
python/flink_agents/plan/tests/tools/resources/function_tool.json
python/flink_agents/runtime/tests/test_built_in_actions.py

Linked issue: #135
Unify the name of ResourceProvider and Resource.

[Feature] Remove the name field of Resource

---

.licenserc.yaml
README.md
dist/pom.xml
dist/src/main/resources/META-INF/NOTICE
dist/src/main/resources/META-INF/licenses/LICENSE.jsoup
dist/src/main/resources/META-INF/licenses/LICENSE.ollama4j
dist/src/main/resources/META-INF/licenses/LICENSE.slf4j
examples/src/main/java/org/apache/flink/agents/examples/ReActAgentExample.java
pom.xml
python/flink_agents/api/execution_environment.py
python/flink_agents/examples/integrate_datastream_with_agent_example.py
python/flink_agents/examples/integrate_table_with_agent_example.py
python/flink_agents/examples/integrate_table_with_react_agent_example.py
python/flink_agents/examples/quickstart/product_improve_suggestion.py
python/flink_agents/examples/quickstart/product_review_analysis.py
python/pyproject.toml
runtime/pom.xml
tools/build.sh

Linked issue: #173 and #193
1. Add flink-agents-dist module to assemble flink-agents jars.
2. Support package flink-agents-dist jar in python wheel.
3. Avoid manually adding the framework jars in user code.
No
No
Later, should modify the build section of document

[package] Refactor the packaging of Flink-Agents

---

docs/content/docs/development/_index.md
docs/content/docs/operations/_index.md

Linked issue: #xxx
Fix the incorrect menu titles
Verified the doc website locally.
n/a
n/a

[hotfix] Correct menu titles

---

python/flink_agents/examples/chat_model_example.py
python/flink_agents/examples/integrate_table_with_react_agent_example.py
python/flink_agents/examples/quickstart/agents/custom_types_and_resources.py
python/flink_agents/examples/quickstart/agents/product_suggestion_agent.py
python/flink_agents/examples/quickstart/agents/review_analysis_agent.py
python/flink_agents/examples/quickstart/react_agent_example.py
python/flink_agents/examples/react_agent_example.py
python/flink_agents/integrations/chat_models/ollama_chat_model.py
python/flink_agents/integrations/chat_models/tests/test_ollama_chat_model.py
python/flink_agents/integrations/chat_models/tests/test_tongyi_chat_model.py
python/flink_agents/integrations/chat_models/tongyi_chat_model.py

Linked issue: #223
Configure the model name uniformly in ChatModelSetup.
ut
no
no

[integration] Configure the model name uniformly in ChatModelSetup.

---

api/src/main/java/org/apache/flink/agents/api/Agent.java
api/src/main/java/org/apache/flink/agents/api/AgentsExecutionEnvironment.java
api/src/main/java/org/apache/flink/agents/api/agents/ReActAgent.java
api/src/main/java/org/apache/flink/agents/api/chat/model/BaseChatModelConnection.java
api/src/main/java/org/apache/flink/agents/api/chat/model/BaseChatModelSetup.java
api/src/main/java/org/apache/flink/agents/api/tools/FunctionTool.java
api/src/main/java/org/apache/flink/agents/api/tools/Tool.java
e2e-test/integration-test/src/main/java/org/apache/flink/agents/integration/test/ReActAgentExample.java
integrations/chat-models/ollama/src/main/java/org/apache/flink/agents/integrations/chatmodels/ollama/OllamaChatModelConnection.java
plan/src/main/java/org/apache/flink/agents/plan/AgentPlan.java
plan/src/main/java/org/apache/flink/agents/plan/actions/ToolCallAction.java
plan/src/main/java/org/apache/flink/agents/plan/tools/FunctionTool.java
plan/src/test/java/org/apache/flink/agents/plan/AgentPlanDeclareChatModelTest.java
plan/src/test/java/org/apache/flink/agents/plan/AgentPlanDeclareToolFieldTest.java
plan/src/test/java/org/apache/flink/agents/plan/AgentPlanDeclareToolMethodTest.java

Linked issue: #216 
Combine add methods to add_resource of `Agent` and `AgentsExecutionEnvironment` in Java.
ut
yes
no

[api][java] Combine add methods to add_resource.

---

plan/src/test/java/org/apache/flink/agents/plan/compatibility/CreateJavaAgentPlanFromJson.java
python/flink_agents/api/events/context_retrieval_event.py
python/flink_agents/examples/rag_agent_example.py
python/flink_agents/plan/actions/context_retrieval_action.py
python/flink_agents/plan/agent_plan.py
python/flink_agents/plan/tests/resources/agent_plan.json

Linked issue: #227
Introduce built-in CONTEXT_RETRIEVAL_ACTION to enable context retrieval (e.g., RAG)
Unit tests and end-to-end RAG agent example.
- Add new events `ContextRetrievalRequestEvent` and `ContextRetrievalResponseEvent`
n/a

[Feature] Introduce built-in CONTEXT_RETRIEVAL_ACTION to enable context retrieval

---

.asf.yaml

Linked issue: #xxx
add homepage link
n/a
n/a
n/a

[hotfix ] add homepage link

---

docs/content/docs/get-started/quickstart/react_agent.md
python/flink_agents/examples/quickstart/react_agent_example.py

Linked issue: #199
Update react agent quickstart doc.
No
No
Yes

[docs] Update react agent quickstart section.

---

docs/content/docs/development/react_agent.md
python/flink_agents/examples/quickstart/agents/custom_types_and_resources.py

Linked issue: #201 
Update react agent development doc.
No
No
Yes

[docs] Update react agent development doc.

---

docs/content/docs/development/integrate_with_flink.md

Linked issue: #206 
Add doc for integration with flink
No
No
Yse

[docs] Update integrate with flink doc.

---

examples/src/main/java/org/apache/flink/agents/examples/WorkflowMultipleAgentExample.java
examples/src/main/java/org/apache/flink/agents/examples/agents/CustomTypesAndResources.java
examples/src/main/java/org/apache/flink/agents/examples/agents/ProductSuggestionAgent.java

Linked issue: #200
Add a multiple agent integration example in java.
```
❯ cd examples; java --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.lang.reflect=ALL-UNNAMED --add-opens java.base/java.text=ALL-UNNAMED --add-opens java.desktop/java.awt.font=ALL-UNNAMED -cp "target/classes:$(mvn dependency:build-classpath -q -Dmdep.outputFile=/dev/stdout)" org.apache.flink.agents.examples.WorkflowMultipleAgentExample; cd ..
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.esotericsoftware.kryo.util.UnsafeUtil (file:/Users/ljiang/.m2/repository/com/esotericsoftware/kryo/kryo/2.24.0/kryo-2.24.0.jar) to constructor java.nio.DirectByteBuffer(long,int,java.lang.Object)
WARNING: Please …
```

[example][java] Add multiple agent integration example

---

docs/content/docs/get-started/overview.md

Linked issue: #197
Update flink agents overview doc.

[docs] Update flink agents overview doc.

---

.github/workflows/build_wheel.yml
.gitignore
pom.xml
python/flink_agents/plan/tests/compatibility/create_python_option_from_java_option.py
tools/build.sh
tools/releasing/create_binary_release.sh
tools/releasing/create_release_branch.sh
tools/releasing/create_source_release.sh
tools/releasing/deploy_staging_jars.sh

Linked issue: #xxx
Add release scripts

[ci] Add release scripts

---

dist/src/main/resources/META-INF/NOTICE
dist/src/main/resources/META-INF/licenses/LICENSE.zstd-jni
tools/.rat-excludes

[hotfix] Update NOTICE and licenses.
